# Generated by Django 2.2.3 on 2019-07-25 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20190721_0646'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='item_code',
        ),
    ]
