# Generated by Django 2.2 on 2019-07-25 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_auto_20190719_1646'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='item_code',
        ),
    ]
